[Cherry Pick] Update release state for recipe bug fix and dependabot version upgrades for 0.12.1
neuralmagic/sparsify pull request #112
Opened 2022-04-29 21:12 UTC by markurtz

2022-04-29 21:13 UTC, markurtz commented on src/sparsify/version.py
> +version_base = "0.13.0"
```suggestion
version_base = "0.12.1"
```

2022-04-29 21:14 UTC, bfineran submitted a review, later dismissed

2022-05-02 13:03 UTC, dhuangnm requested changes

2022-05-02 13:03 UTC, dhuangnm commented on package.json
> +  "version": "0.13.0",
Should the version be 0.12.1 instead?

2022-05-02 13:06 UTC, markurtz commented on package.json
> +  "version": "0.13.0",
ah yep, thanks Dan, misses this one

2022-05-02 13:06 UTC, markurtz commented on package.json
> +  "version": "0.13.0",
```suggestion
  "version": "0.12.1",
```

2022-05-02 13:29 UTC, rahul-tuli approved these changes, later dismissed

2022-05-02 14:07 UTC, bfineran approved these changes, later dismissed

2022-05-02 14:34 UTC, dhuangnm approved these changes, later dismissed

2022-09-15 19:16 UTC, rahul-tuli commented
@markurtz should this be closed?

2022-09-16 15:08 UTC, closed without merging