`sparsify.package` base CLI
neuralmagic/sparsify pull request #125
Opened 2022-08-22 20:40 UTC by rahul-tuli

* Setup directory Structure
* `from sparsify import package` importable + callable function
* A constants file with supported tasks, criterions, and deployment scenarios (Should probably converted to `Enums` or something better than `python lists`)
* Add `click` as a required dependency
* Additional CLI helpers for updated acceptance criterion
* `sparsify.package` cli utility
* setup test directory
* Add tests for CLI
* Setup Entrypoints

2022-08-22 20:55 UTC, corey-nm commented on src/sparsify/package_/cli.py
> +    cls=OptionEatAllArguments,
So this is for choosing a list of metrics to optimize?

Is click.Multiple not usable in this case? https://click.palletsprojects.com/en/8.1.x/options/#multiple-options

2022-08-22 20:57 UTC, corey-nm commented on src/sparsify/package_/cli.py
> +)
So the NotRequiredIf thing is to capture that only dataset or task should be specified?

Can we just have two separate scripts that you invoke or maybe click sub commands based on this?

2022-08-22 20:58 UTC, corey-nm commented on tests/sparsify/package_/test_cli.py
> +from click.testing import CliRunner
Nice tests!! 🎉

2022-08-23 13:21 UTC, rahul-tuli commented on src/sparsify/package_/cli.py
> +    cls=OptionEatAllArguments,
`click.Multiple` needs the corresponding option flag to be specified multiple times i.e `--optimizing-metric accuracy --optimizing-metric compression` whereas this class allows us to do `--optimizing-metric accuracy compression throughput`; it is usable it will just change how we invoke the script. Thoughts on leaning towards one way or the other?

2022-08-23 13:23 UTC, corey-nm commented on src/sparsify/package_/cli.py
> +    cls=OptionEatAllArguments,
I vote for using multiple and adding a short name for this, maybe `-m`? Then it would be `-m accuracy -m compression -m throughput`. Mainly prefer this so we don't have to test/document/maintain our own OptionEatAllArguments.

2022-08-25 01:24 UTC, rahul-tuli commented on src/sparsify/package_/cli.py
> +    cls=OptionEatAllArguments,
> I vote for using multiple and adding a short name for this, maybe `-m`? Then it would be `-m accuracy -m compression -m throughput`. Mainly prefer this so we don't have to test/document/maintain our own OptionEatAllArguments.


on thinking more on this I believe the best course of action would be to remove BOTH OptionEatAllArguments and NotRequiredIf classes.

2022-08-25 01:26 UTC, rahul-tuli commented on src/sparsify/package_/cli.py
> +)
Removed all together; I think it will be easier to handle at the functionality level rather than at cli level.

2022-08-25 01:29 UTC, rahul-tuli commented on src/sparsify/utils/constants.py
> +
The tasks and metrics will be handled in a better way in upcoming diffs

2022-09-01 11:39 UTC, corey-nm commented on src/sparsify/package/cli.py
> +    args: Dict[str, Any] = parse_args()
Whoa I actually really like this way of using click, nice!

2022-09-01 11:39 UTC, corey-nm commented on setup.py
> +            "sparsify.package=sparsify.package.cli:main",
How flexible are we on naming of this command @bfineran? `package` is very vague and makes it sound like it's actually combining things and packaging it up. But in actuality this just selects a model based on metrics right? From product standpoint, less vague the better IMO.

What about `sparsify.pick_model`?

2022-09-01 11:42 UTC, KSGulin commented on src/sparsify/package_/cli.py
> +    cls=OptionEatAllArguments,
According to the requirements document, the interface should allow for multiple accuracy arguments to be passed in as comma separated values. I would argue that space separated values is no worse an option, but best to run it by Mark

2022-09-01 11:57 UTC, KSGulin reviewed
Aside from the comments on optimizing metrics, looks good to me! May have to steal some of this handy click stuff for sparsify.auto

2022-09-01 12:11 UTC, KSGulin commented on src/sparsify/utils/constants.py
> +DATASET_REGISTRY = {
Do you have a use case in mind for the dataset_registry?

2022-09-01 12:11 UTC, KSGulin commented on src/sparsify/utils/constants.py
> +TASK_REGISTRY = {
I'm a big fan of this. Will reference it in `.auto` as well

2022-09-01 14:42 UTC, rahul-tuli commented on src/sparsify/package_/cli.py
> +    cls=OptionEatAllArguments,
@markurtz

2022-09-01 15:53 UTC, kylesayrs commented on src/sparsify/package/cli.py
> +    Utility to fetch a deployment directory for a task based on a
```suggestion
    Utility to fetch a deployment directory for a task based on an
```

Very small nit

2022-09-01 15:56 UTC, kylesayrs approved these changes

2022-09-01 15:56 UTC, kylesayrs commented on src/sparsify/utils/constants.py
> +    "image_classification": TaskInfo(domain="cv", subdomain="classification"),
"-" vs "_" can be handled in preprocessing of the task string, along with `.lower()`ing

2022-09-06 14:46 UTC, rahul-tuli commented on src/sparsify/package/cli.py
> +    Utility to fetch a deployment directory for a task based on a
Good catch! thanks

2022-09-08 13:49 UTC, rahul-tuli commented on src/sparsify/package/cli.py
> +    args: Dict[str, Any] = parse_args()
There was a small bug in the invocation, I had to slightly change it.

2022-09-08 13:50 UTC, rahul-tuli commented
> note - we will need to test a call to `package` that does not mock the API call, to verify end to end functionality independent of API side tests

Will be added as a part of the following diff: #130

2022-09-08 15:45 UTC, KSGulin submitted a review, later dismissed

2022-09-09 14:49 UTC, KSGulin submitted a review, later dismissed

2022-09-12 15:22 UTC, corey-nm commented on src/sparsify/package/cli.py
> +@click.command()
```suggestion
@click.command(context_settings=dict(show_default=True))
```

Will have all options show their default

2022-09-12 15:24 UTC, corey-nm submitted a review, later dismissed
lgtm!

2022-09-13 03:17 UTC, bfineran requested changes
LGTM overall, few quick comments

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/cli.py
> +    default="deployment_directory",
we should have a better default using parts of the stub if possible, or the search params

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/cli.py
> +    "-t",
nit: prefer to get rid of the single character shortcuts, not maintained across our other scripts, could cause confusion if new args added, etc

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/cli.py
> +    help="The criterion to search model for",
let's update to reflect multiple may be chosen and provide example of how to do so

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/cli.py
> +    "--scenario",
let's rename to target or target-deployment

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/cli.py
> +    help="The deployment scenarios to choose from",
```suggestion
    help="Deployment target scenario (ie 'VNNI' for VNNI capable CPUs)",
```

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/cli.py
> +    default=DEPLOYMENT_SCENARIOS[0] if len(DEPLOYMENT_SCENARIOS) else "VNNI",
why would deployment scenarios be empty?

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/package/main.py
> +    print("Package will be invoked")
noting - filled out in #130, let's make sure to explicitly mark for reviewers in future, either through TODO comment or GH comment if pushing to feature branch

2022-09-13 03:17 UTC, bfineran commented on src/sparsify/utils/constants.py
> +    "NO_VNNI",
let's get a different name than `NO_VNNI` either `CPU` or `DEFAULT` maybe

2022-09-15 12:51 UTC, rahul-tuli commented on src/sparsify/package/cli.py
> +@click.command()
Thanks! Updated!

2022-09-15 13:54 UTC, rahul-tuli commented on src/sparsify/package/main.py
> +    raise NotImplementedError
Filled out as a part of diff #130

2022-09-15 14:01 UTC, bfineran approved these changes
changes LGTM 💪

2022-09-15 14:19 UTC, KSGulin approved these changes

2022-09-15 14:30 UTC, merged