[WIP] Add ddp support
neuralmagic/sparsify pull request #126
Opened 2022-08-23 21:23 UTC by KSGulin

With this PR, the torch.distributed module is used for all train runs. Details forthcoming

2022-09-09 13:33 UTC, corey-nm commented
Can't wait for us to drop support for < 1.9 😁

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/auto/tasks/args.py
> +    def serialize_to_cli_string(self, dashed_keywords) -> List[str]:
```suggestion
    def serialize_to_cli_string(self, underscores_to_dashes: bool) -> List[str]:
```

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/auto/tasks/args.py
> +                    args_string_list.append(key)
Would negative flags (for example `--no-eval` or something like that) have a bool of false?

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/version.py
> +version_base = "1.2.0"
Is this supposed to be in this PR?

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/auto/utils/error_handler.py
> +        if exception:
recommend doing guard for this bigger if else for less indents

```
if exception is None:
    self._caught_memory_error_on_last_attempt = False
    return

...
```

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/auto/tasks/transformers/runner.py
> +        # self.train_args.gradient_accumulation_steps *= 2
Is this intentional?

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/auto/tasks/object_detection/yolov5/args.py
> +    evolve: Tuple[bool, int] = Field(
What's the reasoning for there being additional arguments in some of the CLI versions? I see this is also the case for IC

2022-09-09 13:53 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +    from torch.distributed.run import main as launch_ddp
As asked in slack, could you use `from torch.distributed.run import run`?

https://github.com/pytorch/pytorch/blob/master/torch/distributed/run.py#L738

2022-09-09 16:57 UTC, KSGulin commented on src/sparsify/auto/tasks/args.py
> +                    args_string_list.append(key)
An arg like `--no-eval` being present in the cli command should be interpreted as a bool of true in code. e.g. `no_cuda` in transformers. This is a good point to keep an eye out for contrary examples in our integrations

2022-09-09 16:59 UTC, KSGulin commented on src/sparsify/version.py
> +version_base = "1.2.0"
Yep we'll have to bump it again to 1.3 before alpha lands. To my threshold it's a smaller enough rider to keep it in 🙂

2022-09-09 16:59 UTC, KSGulin commented on src/sparsify/auto/utils/error_handler.py
> +        if exception:
Good call

2022-09-09 16:59 UTC, KSGulin commented on src/sparsify/auto/tasks/transformers/runner.py
> +        # self.train_args.gradient_accumulation_steps *= 2
Nope, thanks for catching it!

2022-09-09 17:03 UTC, KSGulin commented on src/sparsify/auto/tasks/object_detection/yolov5/args.py
> +    evolve: Tuple[bool, int] = Field(
These are re-definitions of existing args in the API version. The reason is that in some cases there is no common type representation that will cover both CLI and API usage. With enough post-processing logic to cover all edge cases this could probably be patched (having taken a look at it, it's far from trivial unfortunately), but it falls at pretty low priority at this moment.

However, I don't love the approach of re-definition I'm using here. I considered changing the type programmatically, but then you lose quite a bit of readability in terms of someone just opening the file and reading what type an arg needs to be. Suggestions welcome 🙂

2022-09-09 17:06 UTC, KSGulin commented on src/sparsify/auto/tasks/runner.py
> +    from torch.distributed.run import main as launch_ddp
This wouldn't get rid of the CLI/API duality unfortunately. One of the args that `torch.distributed.run` takes is `args.training_script_args` which is a string of cli args for sparseml in our use case, to be used via a subprocess call many layers deeper in torch

2022-09-09 18:07 UTC, corey-nm commented on src/sparsify/auto/tasks/object_detection/yolov5/args.py
> +    evolve: Tuple[bool, int] = Field(
What about a base class that doesn't have the different fields (i.e. it wouldn't have evolve/freeze), then add two subclasses of that, one with API types one with CLI types.

```
class _Yolov5BaseArgs(BaseModel):
    ...

class Yolov5TrainArgsAPI(_Yolov5BaseArgs):
    evolve: Optional[int] = ...
    freeze: List[int] = ...

class Yolov5TrainArgsCLI(_Yolov5BaseArgs):
    evolve: Tuple[bool, int] = ...
    freeze: str = ... 
```

2022-09-09 18:10 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +        )
```suggestion
        self.use_distributed_training = (
            not (disable_ddp or os.environ.get("NM_AUTO_DISABLE_DDP"))
        )
```

2022-09-09 18:15 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +    from torch.distributed.run import main as launch_ddp
Okay I think i'm understanding this more now, makes sense to me!

2022-09-09 18:16 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +            False if (disable_ddp or os.environ.get("NM_AUTO_DISABLE_DDP")) else True
Does this same logic need to be applied to the import statements where the API vs CLI args is selected?

2022-09-09 18:17 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +    disable_ddp = False
global variable all caps?

2022-09-12 12:00 UTC, KSGulin commented on src/sparsify/auto/tasks/runner.py
> +            False if (disable_ddp or os.environ.get("NM_AUTO_DISABLE_DDP")) else True
Yes, great catch!

2022-09-12 12:01 UTC, KSGulin commented on src/sparsify/auto/tasks/object_detection/yolov5/args.py
> +    evolve: Tuple[bool, int] = Field(
Adopted. It adds an extra class, but improves readability. A net positive in my view

2022-09-12 13:46 UTC, corey-nm requested changes

2022-09-12 13:46 UTC, corey-nm commented on src/sparsify/auto/tasks/object_detection/yolov5/runner.py
> +            shutil.rmtree(os.path.dirname(self.train_args.project))
Can you expand on this change? Also should the isdir check be on the dirname of project (so its the same as what's removed)?

2022-09-12 13:46 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +                    warnings.warn(
Should all of these use logger.warn additionally/instead?

2022-09-12 13:46 UTC, corey-nm commented on src/sparsify/auto/utils/error_handler.py
> +        elif self._max_memory_stepdowns >= self._max_memory_stepdowns:
Is this the intention?
```suggestion
        elif len(self._caught_memory_errors) >= self._max_memory_stepdowns:
```

2022-09-12 13:46 UTC, corey-nm commented on src/sparsify/auto/utils/error_handler.py
> +                "times"
nit: add errors to this output?

2022-09-13 12:31 UTC, KSGulin commented on src/sparsify/auto/tasks/runner.py
> +    disable_ddp = False
updated to make the flag handling cleaner

2022-09-13 12:40 UTC, KSGulin commented on src/sparsify/auto/tasks/runner.py
> +                    warnings.warn(
we definitely want to add some robust logging in the near future, but it's not scoped out as part of the alpha

2022-09-13 12:42 UTC, KSGulin commented on src/sparsify/auto/utils/error_handler.py
> +        elif self._max_memory_stepdowns >= self._max_memory_stepdowns:
Yep, thanks! The result of too many quick changes to one function

2022-09-13 12:44 UTC, KSGulin commented on src/sparsify/auto/utils/error_handler.py
> +                "times"
Most of the time these errors aren't very helpful. Plan to do a more thorough survey of the out of memory errors in a future sprint to develop a more informed approach to filtering and returning them.

2022-09-14 15:17 UTC, KSGulin commented on src/sparsify/auto/tasks/object_detection/yolov5/runner.py
> +            shutil.rmtree(os.path.dirname(self.train_args.project))
Good find. I think there was a reason for this earlier in development that doesn't stand anymore. Updated

2022-09-14 17:42 UTC, KSGulin commented
Solved the issue where ddp would attempt to re-use the same port by manually fetching an open port

2022-09-14 17:47 UTC, bfineran submitted a review, later dismissed

2022-09-15 13:42 UTC, corey-nm commented on src/sparsify/auto/tasks/runner.py
> +    return sock.getsockname()[1]
do you need to close sock in this function so it doesn't own the port?

2022-09-15 14:43 UTC, KSGulin commented on src/sparsify/auto/tasks/runner.py
> +    return sock.getsockname()[1]
Interestingly it worked fine, I think because it wasn't listening on the port yet. But good call, added a call to close

2022-09-15 14:45 UTC, corey-nm approved these changes, later dismissed
lgtm! nice work

2022-09-15 14:49 UTC, corey-nm approved these changes

2022-09-15 14:50 UTC, bfineran approved these changes

2022-09-15 15:11 UTC, merged