Refactor package function to make a call to the backend service
neuralmagic/sparsify pull request #130
Opened 2022-08-31 23:01 UTC by rahul-tuli

This PR refactors code from #127 into a backend service call and appropriate functions were added in the backend in [diff #1](https://github.com/neuralmagic/model-api-service/pull/1)

Also depends on sparsezoo diff [#235](https://github.com/neuralmagic/sparsezoo/pull/235)

2022-09-01 11:41 UTC, corey-nm reviewed
Looks fine for now - obv has to wait for other PR landed

2022-09-01 12:07 UTC, KSGulin commented on src/sparsify/package/cli.py
> +    print(package(**args))
I think we'll want a custom string template for package. It would essentially tell the user that a model has been download for them to `some_directory` and it would provide deployment instructions in text form (both printing the deployment instructions to console and saving them to a .txt file for the user). I wouldn't worry about the content of the template at the moment, but it would be nice to set up the logic to handle the template in this PR. The logic for generating task-specific deployment instructions will be shared between `.package` and `.auto`, so whoever gets to it first should include it in a general sparsify utils folder

2022-09-08 14:01 UTC, rahul-tuli commented on src/sparsify/package/cli.py
> +    print(package(**args))
Adding a convenience function to take care of this; We can sync on the actual template accordingly

2022-09-09 14:44 UTC, corey-nm requested changes

2022-09-09 14:44 UTC, corey-nm commented on src/sparsify/package/config.py
> +BACKEND_URL = BASE_URL + _END_POINT
Let's move this into a function

```python
def get_backend_url() -> str:
    ...
```

Mainly so os.getenv is called at runtime instead of import time and to reduce amount of global variables

2022-09-09 14:44 UTC, corey-nm commented on src/sparsify/package/cli.py
> +        return "No Relevant Model Stubs found"
Let's handle this in main instead

2022-09-15 14:13 UTC, rahul-tuli commented on src/sparsify/package/cli.py
> +        return "No Relevant Model Stubs found"
I would like to keep the CLI as agnostic of the actual logic as possible

2022-09-30 17:32 UTC, bfineran commented on src/sparsify/package/config.py
> +_DEFAULT_BASE_URL = "http://0.0.0.0:8000"
let's update this to 
```suggestion
_DEFAULT_BASE_URL = "https://api.neuralmagic.com"
```

2022-09-30 17:32 UTC, bfineran commented on src/sparsify/package/config.py
> +    return os.getenv("SPARSIFY_BACKEND_URL", default=_DEFAULT_BASE_URL)
nice

2022-09-30 17:44 UTC, bfineran approved these changes

2022-09-30 17:47 UTC, KSGulin approved these changes
LGTM

2022-09-30 17:47 UTC, KSGulin commented on src/sparsify/package/main.py
> +    :param directory: str A local existing directory path to download the deployment
nit: I prefer not to annotate the doc string with the param types since they're already in the type hints and it makes the doc string a bit harder to read. But that's just my preference, feel free to ignore

2022-09-30 18:06 UTC, corey-nm approved these changes
lgtm!

2022-09-30 18:29 UTC, rahul-tuli commented on src/sparsify/package/main.py
> +    :param directory: str A local existing directory path to download the deployment
Will fix in another diff, thank you for catching this

2022-09-30 18:29 UTC, merged