Remove config creator
neuralmagic/sparsify pull request #136
Opened 2022-09-16 14:48 UTC by KSGulin

This PR removes the config creator from sparsify and replaces the functionality with calls to the Neural Magic API.

Note that in this PR the calls to the API are directed to local host. This address will be properly updated before merging sparsify.alpha into main, once the API goes live. 

**Testing**
covered by automatic pytest testing and integration tests

Ran a manual test by running ./bin/run-local within this repo, followed by sparsify.auto --task object_detection --data coco128.yaml in sparsify

2022-09-20 15:17 UTC, corey-nm approved these changes

2022-09-20 15:17 UTC, corey-nm commented on src/sparsify/auto/api/main.py
> +        configs.append(SparsificationTrainingConfig(**response.json()))
Yeah as mentioned in other PR, I think doing something like:
```suggestion
        config_dict = response.json()
        if config_dict is None:
            break
        config = SparsificationTrainingConfig(**config_dict)
```
Could be more explicit. Unless there's something else that we may want to include in the completion dict?

2022-09-20 15:17 UTC, corey-nm commented on src/sparsify/auto/api/main.py
> +        runner_outputs.append(runner.run())
I think moving to list of tuples could help this out. You could do:
```python
history = []
config = ... # initial request
while ...:
    runner = ...
    metrics = runner.run()
    history.append((config, metrics))
    response = requests.post(... json={'history': history})
```

2022-09-20 15:17 UTC, corey-nm commented on src/sparsify/auto/api/main.py
> +        if len(configs) == 0:
can you move this out of the loop to just always run?

2022-09-20 15:18 UTC, corey-nm requested changes
Ack sorry meant to just comment instead approve

2022-09-21 13:51 UTC, bfineran reviewed
LGTM overall, minor comments

2022-09-21 13:51 UTC, bfineran commented on src/sparsify/auto/api/main.py
> +                json=api_args.dict(),
let's move this into a helper function - prefer to separate API query handling from the main logic loop

2022-09-21 13:51 UTC, bfineran commented on src/sparsify/auto/api/main.py
> +        )
ditto

2022-09-21 13:51 UTC, bfineran commented on src/sparsify/auto/api/main.py
> +        if response.json().get("tuning_complete"):
what is the expected response model here? would it make sense to break into something more structured, or over-engineering for now?

2022-09-21 13:51 UTC, bfineran commented on tests/sparsify/auto/autosparse/test_registered_tasks.py
> +    assert [char in response.text for char in ["]", "["]]
took a second to read the list, not sure if `char in "[]"` would be any easier. nbd

2022-09-21 13:51 UTC, bfineran commented on tests/sparsify/auto/autosparse/test_registered_tasks.py
> +    config_tasks = [TASK_REGISTRY[task] for task in ast.literal_eval(response.text)]
why do we need ast here?

2022-09-27 16:49 UTC, KSGulin commented on src/sparsify/auto/api/main.py
> +        configs.append(SparsificationTrainingConfig(**response.json()))
We want to be explicit that the return is a signal that early termination condition was met. None leaves too much room for ambiguity

2022-09-27 17:54 UTC, KSGulin commented on src/sparsify/auto/api/main.py
> +        runner_outputs.append(runner.run())
Good call, updated 🙂

2022-09-27 17:55 UTC, KSGulin commented on src/sparsify/auto/api/main.py
> +                json=api_args.dict(),
Good call, done

2022-09-27 17:56 UTC, KSGulin commented on src/sparsify/auto/api/main.py
> +        if response.json().get("tuning_complete"):
Over-engineering I think. We'd introduce an ambiguity of dict -> pydantic model assignment which could definitely be engineered around, but it doesn't more closer to the ideal than this also less than ideal approach

2022-09-27 18:10 UTC, bfineran approved these changes, later dismissed

2022-09-27 18:36 UTC, bfineran approved these changes, later dismissed

2022-09-28 14:16 UTC, corey-nm approved these changes, later dismissed
lgtm! 🎉

2022-10-06 14:06 UTC, corey-nm requested changes
Would be good to add some tests for the best models logic for expected directory structure/saved models

2022-10-06 17:42 UTC, KSGulin commented on src/sparsify/auto/api/main.py
> +    ):
Good catch

2022-10-11 13:59 UTC, KSGulin commented on src/sparsify/auto/tasks/object_detection/yolov5/runner.py
> +            else "weights/last.pt"
Sure, updated

2022-10-11 13:59 UTC, KSGulin commented on src/sparsify/auto/tasks/runner.py
> +    export_model_kwarg: Optional[str] = None
I agree with this in principle, but devs rather than users would be setting this value when adding a new integration. Opting to keep as is for now and revisit once alpha version is in a more stable state

2022-10-11 13:59 UTC, KSGulin commented on src/sparsify/auto/api/main.py
> +                    api_args.save_directory, metrics_list.index(max(metrics_list))
Flow has been updated and tests added to cover it. Resolving this conversation and the ones following it. Feel free to leave comments on the new flow 🙂

2022-10-11 14:34 UTC, KSGulin commented
@corey-nm great call on the trial management testing. Added testing of the main flow in `test_main.py`

2022-10-11 16:02 UTC, rahul-tuli reviewed
Minors nitpicks. Great Job!

2022-10-11 16:02 UTC, rahul-tuli commented on tests/sparsify/auto/autosparse/test_main.py
> +        pass
Same suggestion as above

2022-10-11 16:02 UTC, rahul-tuli commented on tests/sparsify/auto/autosparse/test_main.py
> +
nice

2022-10-11 19:43 UTC, bfineran reviewed
lgtm pending comments, great work

2022-10-11 19:43 UTC, bfineran commented on src/sparsify/auto/api/main.py
> +        if len(best_n_trial_metrics) > maximum_trial_saves:
nit: add comment or move to helper function

2022-10-11 19:43 UTC, bfineran commented on src/sparsify/utils/constants.py
> +NEURAL_MAGIC_API_ADDRESS = "http://0.0.0.0:8000"
yup, needs to match what we did for package

2022-10-12 11:37 UTC, KSGulin commented on src/sparsify/auto/tasks/image_classification/runner.py
> +        return os.path.join(self.train_args.save_dir, self.train_args.model_tag)
Depends on what is specified by the user. It is meant to conform to the IC API, which accepts relative or absolute paths. The default path is relative

2022-10-12 11:38 UTC, KSGulin commented
Thanks for the thorough comments. Addressed 🙂 
@rahul-tuli I updated the NM API calls to be centralized, which touched sparsify.package. Please take a look

2022-10-12 16:00 UTC, corey-nm commented on setup.py
> +_deps = ["pydantic>=1.8.2", "pyyaml>=5.0.0", "click~=8.0.0", "torch==1.9.1"]
should we do torch>=1.9.0?

2022-10-12 16:00 UTC, corey-nm commented on src/sparsify/auto/api/api_models.py
> +            "Maximum number of hours to train before returning best trained " "model."
optional nit
```suggestion
            "Maximum number of hours to train before returning best trained model."
```

2022-10-12 16:00 UTC, corey-nm commented on src/sparsify/auto/api/api_models.py
> +        ),
optional nit: what does None mean for this value?

2022-10-12 16:00 UTC, corey-nm commented on src/sparsify/auto/api/main.py
> +    while (
flow for this is super clean now, nice! 🚀

2022-10-12 16:00 UTC, corey-nm commented on tests/sparsify/auto/autosparse/test_main.py
> +_SAVE_DIRECTORY = "./test_main"
Can this be done with `tmp_path` fixture from pytest?

2022-10-12 16:00 UTC, corey-nm commented on src/sparsify/auto/api/main.py
>      api_args = APIArgs.from_cli()
I think this function should be split to make testing easier:
```python
def main():
    api_args = ApiArgs.from_cli()
    run(api_args)

def run(api_args: APIArgs):
    ...
```

2022-10-12 16:00 UTC, corey-nm commented on tests/sparsify/auto/autosparse/test_main.py
> +    assert os.path.exists(_SAVE_DIRECTORY)
Can you add tests for what the save directory should contain? Will it just be the artifact directories? Will there be more?

2022-10-12 20:36 UTC, KSGulin commented on src/sparsify/auto/api/main.py
>      api_args = APIArgs.from_cli()
Hmm I see the merit in the suggestion. I'm not sure I entirely agree. I would say let's table this consideration until later. The granularity here is too fine to consider for an alpha version which will go through more product-driven revisions

2022-10-12 20:37 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +)
Same as above

2022-10-13 13:00 UTC, KSGulin commented on src/sparsify/auto/tasks/transformers/runner.py
> +        self._model_save_name = ""
Yes, the transformers integration targets whole directories rather than specific files

2022-10-13 13:01 UTC, KSGulin commented on src/sparsify/auto/api/api_models.py
> +        title="task",
Holdover from a previous architecture and no longer necessary for SparsificationTrainingConfig. Good catch!

2022-10-13 13:04 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +_SAVE_DIRECTORY = "./test_main"
I do like the elegance of tmp_path, but in this case it would complicate the design, since tmp_path is only accessible within the test and the save directory is needed prior to test start

2022-10-13 13:10 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +    assert os.path.exists(_SAVE_DIRECTORY)
Good call, updated 🙂

2022-10-13 13:15 UTC, corey-nm commented on tests/sparsify/auto/autosparse/test_main.py
> +    )
Nice! Assuming there should only be MAXIMUM_SAVES sub dirs in run_artifacts, which is what the loop below is testing? Can you add a check that there isn't anything else in that dir?

Any then what's in the deployment directory again?

2022-10-13 13:15 UTC, corey-nm commented on tests/sparsify/auto/autosparse/test_main.py
> +    assert os.listdir(directory_path), f"Directory empty:  {directory_path}"
This is being addressed below, resolving

2022-10-13 13:32 UTC, corey-nm commented on setup.py
> +_deps = ["pydantic>=1.8.2", "pyyaml>=5.0.0", "click~=8.0.0", "torch==1.9.1"]
But sparseml isn't a dependency of this package right? Is pip not smart enough  when you run `pip install sparseml sparsify` to figure out that it needs 1.9.1?

2022-10-13 14:31 UTC, KSGulin commented on setup.py
> +_deps = ["pydantic>=1.8.2", "pyyaml>=5.0.0", "click~=8.0.0", "torch==1.9.1"]
sparseml is a requirement, under `_nm_deps`

2022-10-13 14:38 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +    )
Updated. The deployment directory contains whatever you need to deploy. It will always contain an .onnx file and may or may not contain sample in/out. Anything that sparseml export commands create would be contained here

2022-10-13 14:39 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +_SAVE_DIRECTORY = "./test_main"
The scope still wouldn't set it on the global namespace right? The values that are getting patched depend on save_directory, so we'd need the path defined before we patch

2022-10-13 14:43 UTC, corey-nm commented on setup.py
> +_deps = ["pydantic>=1.8.2", "pyyaml>=5.0.0", "click~=8.0.0", "torch==1.9.1"]
Gotcha okay

2022-10-13 14:43 UTC, corey-nm commented on src/sparsify/auto/api/api_models.py
> +        title="maximum_trial_saves",
Title here as well?

2022-10-13 14:45 UTC, corey-nm commented on tests/sparsify/auto/autosparse/test_main.py
> +    )
```suggestion
    assert sorted(os.listdir(output_path)) == ["deployment", "logs", "run_artifacts"]
```
?

2022-10-13 14:57 UTC, KSGulin commented on src/sparsify/auto/api/api_models.py
> +        title="maximum_trial_saves",
`APIArgs` does still need the title field for automatic cli arg construction. It's more of a pedantic (heh) failsafe than a hard requirement, but still nice to have

2022-10-13 14:58 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +    )
Great suggestion

2022-10-13 14:59 UTC, KSGulin commented on tests/sparsify/auto/autosparse/test_main.py
> +_SAVE_DIRECTORY = "./test_main"
Yeah I would say over-engineering at this point. But I would like to clean up this test after alpha launch 🙂

2022-10-13 15:05 UTC, corey-nm commented on src/sparsify/auto/api/api_models.py
> +        title="maximum_trial_saves",
Oooh gotcha good to know

2022-10-13 15:24 UTC, corey-nm approved these changes, later dismissed
🥳

2022-10-13 15:31 UTC, corey-nm approved these changes

2022-10-13 15:35 UTC, merged