`sparsify.init` CLI to create an project/experiment
neuralmagic/sparsify pull request #192
Opened 2023-04-17 14:17 UTC by rahul-tuli

This PR represents the base feature branch for `sparsify.init` cli push

```bash

Usage: sparsify.init [OPTIONS]
  sparsify.init CLI utility to initialize an experiment such that it will
  provision all local and cloud resources necessary, additionally also allows
  users to update hyper-param(s) before applying
Options:
  --experiment-type [sparse-transfer|one-shot|training-aware]
                                  The type of the experiment to run
  --use-case [image_classification|object_detection|question_answering|
  segmentation|sentiment_analysis|text_classification|token_classification]
                                  The task this model is for
  --project-id TEXT               Id of the project this run belongs to.
  --experiment-id TEXT            Id of the experiment this run belongs to.
  --working-dir TEXT              Path to save the deployment ready model to.
  --model TEXT                    Path to model
  --model-id TEXT                 sparsify model id
  --data TEXT                     Path to dataset folder containing training
                                  data and optionally validation data
  --eval-metric [kl|accuracy|mAP|recall|f1]
                                  Metric that the model is evaluated against
                                  on the task. None means it is based on
                                  --use-case.  [default: kl]
  --train-samples INTEGER         Number of samples to use from the dataset
                                  for processing. None means the entire
                                  dataset.
  --val-samples INTEGER           Number of samples to use from the dataset
                                  for processing. None means the entire
                                  dataset.
  --help                          Show this message and exit.  [default:
                                  False]
```

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204285970834853

2023-05-01 10:36 UTC, KSGulin reviewed
Code looks good! Left some comments on the CLI

2023-05-01 10:36 UTC, KSGulin commented on src/sparsify/cli/init.py
> +                                  --use-case.  [default: kl]
Could use some clarification on what the default behavior is. Does it get determined by use case or default to kl?

2023-05-01 10:36 UTC, KSGulin commented on src/sparsify/cli/init.py
> +                                  for processing. None means the entire
nit: identical description as `--train-samples`

2023-05-01 10:49 UTC, KSGulin approved these changes

2023-05-01 11:28 UTC, KSGulin commented on src/sparsify/cli/init.py
> +  --experiment-type [sparse-transfer|one-shot|training-aware]
@bfineran should dense-training be added here as well?

2023-05-02 11:55 UTC, bfineran commented on src/sparsify/cli/init.py
> +  --experiment-type [sparse-transfer|one-shot|training-aware]
we will add later depending, dense-training may be a local only mode so wouldn't be initialized

2023-05-02 12:12 UTC, bfineran requested changes

2023-05-02 12:12 UTC, bfineran commented on src/sparsify/cli/init.py
> +def create_session() -> requests.Session:
let's get the request refactored so it can be easily shared and used with other flows (ie apply, maybe login)

2023-05-02 12:12 UTC, bfineran commented on src/sparsify/cli/init.py
> +    _LOGGER.info("Health check passed")
let's remove this log, no need to know if it passes if we error on fail

2023-05-02 12:12 UTC, bfineran commented on src/sparsify/cli/init.py
> +        raise RuntimeError("Health check failed")
let's change the error message to something closer to "unable to access sparsify API" and add the response text. as is, we don't know if it's a client or server side error

2023-05-02 12:12 UTC, bfineran commented on src/sparsify/cli/init.py
> +def create_session() -> requests.Session:
maybe can refactor into a simple class that on instantiation creates a session and does a health check, then has `_post` and `_get` methods that can take care of some of the repeated boilerplate below given the relative route and payload

2023-05-02 13:06 UTC, rahul-tuli commented on src/sparsify/cli/init.py
> +    _LOGGER.info("Health check passed")
Removed!

2023-05-02 13:11 UTC, rahul-tuli commented on src/sparsify/cli/init.py
> +def create_session() -> requests.Session:
Nice suggestion, adding it in

2023-05-02 13:17 UTC, rahul-tuli commented on src/sparsify/cli/init.py
> +        raise RuntimeError("Health check failed")
Accepted, change coming up!

2023-05-02 13:36 UTC, rahul-tuli commented on src/sparsify/cli/init.py
> +                                  --use-case.  [default: kl]
Updated!

2023-05-02 13:37 UTC, rahul-tuli commented on src/sparsify/cli/init.py
> +                                  for processing. None means the entire
Updated!

2023-05-11 17:12 UTC, bfineran requested changes
Great work - please review comments and let me know if you have any questions

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +    def _get_token_response(self, scope: str = "pypi:read") -> Dict[Any, Any]:
nit: private methods to bottom

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +        _LOGGER.info("Successfully authenticated with Neural Magic Account API key. ")
move to debug

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/init.py
> +    client.health_check()
looking more into the code - we can keep the credentials class, however, for usage of the client, let's have the client just create the credentials under the hood to simplify the flow (we don't really need the credentials for anything once the user is logged in).

This way, we can add a getter for the access token that either returns the already fetched, valid access token, or refreshes if necessary

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +    "SparsifySession",
let's move all of the credentials/client flow into their own file `client.py` or something

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +        )
let's move this to `set_access_token` in `SparsifySession`, that way in the future when we need to update the access token, it will be easy

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +        _LOGGER.info(f"Experiment created with id: {experiment_id}")
any logs in the client class should be in debug mode. if we want to expose anything at the user experience level, that should be coming from the script calling into this function

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +                self.get(url=f"{endpoint}/{model_id}")
what do we do in the success case here?

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +        _LOGGER.info("Creating a new analysis")
same on info -> debug

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +        _LOGGER.info(f"Updating experiment status to {status}")
info -> debug

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +        _LOGGER.info(f"Updating experiment status to {eval_metric}")
info -> debug

2023-05-11 17:12 UTC, bfineran commented on src/sparsify/utils/helpers.py
> +    def create_analysis(
let's rename to `upload_` since the analysis is already "created"

2023-05-12 10:14 UTC, rahul-tuli commented on src/sparsify/utils/helpers.py
> +                self.get(url=f"{endpoint}/{model_id}")
if a model_id is provided, we validate that it's a correct model_id which exists in sparsify cloud

2023-05-12 10:35 UTC, rahul-tuli commented on src/sparsify/login.py
> +        _LOGGER.info(
To prevent a user from re-entering the api-key, if sparsify.login has been successfully invoked before, i.e we have a valid credentials file stored on disk

2023-05-12 12:41 UTC, KSGulin approved these changes
Great stuff!

2023-05-12 15:10 UTC, bfineran approved these changes

2023-05-12 15:10 UTC, bfineran commented on src/sparsify/utils/client.py
> +            # read api key from environment variable
need a debug log here

2023-05-12 15:46 UTC, merged