Sparsify.package
neuralmagic/sparsify pull request #203
Opened 2023-05-09 13:52 UTC by rahul-tuli

A very basic version of `sparsify.package` that when given a deployment directory and a task displays instructions on how to deploy the directory with the dockerfile supplied with this repo

```bash
(sparsify.package) sparsify.package --deployment-dir ~/models --task ic

        Use the dockerfile in /home/ubuntu/github_projects/sparsify/src/docker/Dockerfile to build sparsify
        image and run the `deepsparse.server`

        Run the following command inside `/home/ubuntu/github_projects/sparsify/src/docker`
        directory (Note: replace <API_KEY> with appropriate sparsify api key):

        ```bash
        docker build --build-arg SPARSIFY_API_KEY=<API_KEY> -t sparsify_docker . \
            && docker run -it -v /home/ubuntu/models:/home/deployment  \
                sparsify_docker sparsify.server \
                    --task ic --model_path /home/deployment
        ```
```

Usage:
```bash
Usage: sparsify.package [OPTIONS]

Options:
  --version                       Show the version and exit.  [default: False]
  --task [image_classification|object_detection|segmentation|question_answering|
  text_classification|sentiment_analysis|token_classification]
                                  The task to package depoyment directory for
                                  [required]
  --deployment-dir DIRECTORY      The directory containing the deployment
                                  files to package  [required]
  --help                          Show this message and exit.  [default:
                                  False]
```

2023-05-16 11:54 UTC, KSGulin approved these changes

2023-05-19 21:41 UTC, bfineran requested changes

2023-05-19 21:41 UTC, bfineran commented on docker/Dockerfile
> +RUN sparsify.login --api-key $SPARSIFY_API_KEY
why do we need sparsify and sparsifyml in the deployment dockerfile? We should only be installing deepsparse as this is a lightweight deployment container

2023-05-19 21:41 UTC, bfineran commented on src/sparsify/package.py
> +    dockerfile_path = dockerfile_directory / "Dockerfile"
we should be copying the dockerfile into the deployment directory and providing instructions relative to that

2023-05-23 10:58 UTC, rahul-tuli commented
Reopened as #213 due to branch protection rules!

2023-05-23 10:58 UTC, closed without merging